# Generated by Django 5.2.4 on 2025-07-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('form_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_date', models.DateField()),
                ('status', models.CharField(default='saved', max_length=20)),
                ('tread_diameter_new', models.CharField(help_text='e.g., 915 (900-1000)', max_length=50)),
                ('last_shop_issue_size', models.CharField(help_text='e.g., 837 (800-900)', max_length=50)),
                ('condemning_dia', models.CharField(help_text='e.g., 825 (800-900)', max_length=50)),
                ('wheel_gauge', models.CharField(help_text='e.g., 1600 (+2,-1)', max_length=50)),
                ('variation_same_axle', models.CharField(max_length=20)),
                ('variation_same_bogie', models.CharField(max_length=20)),
                ('variation_same_coach', models.CharField(max_length=20)),
                ('wheel_profile', models.CharField(max_length=100)),
                ('intermediate_wwp', models.CharField(max_length=50)),
                ('bearing_seat_diameter', models.CharField(max_length=50)),
                ('roller_bearing_outer_dia', models.CharField(max_length=50)),
                ('roller_bearing_bore_dia', models.CharField(max_length=50)),
                ('roller_bearing_width', models.CharField(max_length=50)),
                ('axle_box_housing_bore_dia', models.CharField(max_length=50)),
                ('wheel_disc_width', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Wheel Specification',
                'verbose_name_plural': 'Wheel Specifications',
                'db_table': 'wheel_specification',
                'ordering': ['-created_at'],
            },
        ),
    ]
